name = "staticsite"
main = "worker.js"  # This is your Worker script
compatibility_date = "2025-04-22"

# This tells Wrangler where to find your static files (e.g., your Vite build output)
[site]
bucket = "./dist"

[build]
command = "vite build"
