name = "staticsite"
compatibility_date = "2025-04-22"
workers_dev = true
main = "worker.js"



[site]
bucket = "./dist"
entry-point = "worker.js"  # Your Worker script entry point

[build]
command = "vite build" 