name = "staticsite"
compatibility_date = "2025-04-16"
workers_dev = true
type = "javascript"

[site]
bucket = "./dist"
entry-point = "."  # assuming worker.js is in project root

[build]
command = "vite build"